name: Pizza Planet CI
on:
  pull_request:
    branches: [ main ]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          . venv/bin/activate
          pytest --cov=app --cov-report=term --cov-fail-under=80 ./app/test
