with:
  python-version: "3.10"

steps:
  - name: Set up virtual environment
    run: |
      python -m venv venv
      . venv/bin/activate

  - name: Install project dependencies
    run: |
      . venv/bin/activate
      pip install -r requirements.txt

  - name: Initialize and migrate database
    run: |
      . venv/bin/activate
      python manage.py db init
      python manage.py db migrate
      python manage.py db upgrade

  - name: Execute tests with coverage
    run: |
      . venv/bin/activate
      pytest --cov=app --cov-report=term --cov-fail-under=80 ./app/test

